### ISSUE TITLE
Build Android falha na main: react-native-android-widget e @react-native-menu/menu incompatíveis com RN 0.86

### ISSUE THREAD

**Issue by rechcosta** [nossa-ufsc/mobile#6]
## Descrição do Bug

O build de Android falha na `main` (9884b54) a partir de um clone limpo. Duas dependências nativas não compilam contra o React Native 0.86, introduzido em `54b3f50 (feat: update to expo 57)`.

### 1. `react-native-android-widget` — `cannot find symbol: class CSSBackgroundDrawable`

O `package.json` declara `"react-native-android-widget": "^0.17.0"`. Em semver, o caret em versões `0.x` não avança de minor (`^0.17.0` = `>=0.17.0 <0.18.0`), então o range resolve para **0.17.3**, publicada em 03/01/2026 — cinco meses antes do React Native 0.86. Essa versão importa `com.facebook.react.uimanager.drawable.CSSBackgroundDrawable`, classe interna removida no RN 0.86.

Nenhuma reinstalação resolve: o range trava a resolução em 0.17.x, e as versões 0.18.0 a **0.21.0** (11/07/2026, posterior ao RN 0.86) nunca são alcançadas.

O peerDependency da 0.17.3 é `expo: >=54.0.0`, que o Expo 57 satisfaz — por isso nenhum aviso é emitido na instalação.

**Correção validada:** bump para `^0.21.0`.

### 2. `@react-native-menu/menu` — falha em `compileDebugKotlin`

```
e: MenuView.kt:50:3 'setHitSlopRect' overrides nothing.
e: MenuView.kt:51:11 Unresolved reference 'setHitSlopRect'.
e: MenuViewManagerBase.kt:126:12 Unresolved reference 'setHitSlopRect'.
e: MenuViewManagerBase.kt:128:12 Unresolved reference 'setHitSlopRect'.
e: MenuViewManagerBase.kt:209:10 Unresolved reference 'setOverflow'.
```

O RN 0.86 converteu `ReactViewGroup.setHitSlopRect()` em propriedade Kotlin `hitSlopRect` e removeu `setOverflow`. A versão 2.0.0 (último release npm, 10/09/2025) ainda usa a API antiga.

O upstream **já corrigiu** na branch `master` — commit `e42e5ac8` (29/06/2026, *"fix: android build on Expo SDK 55+56 / RN 0.83 / Kotlin 2.x"*), que passou a usar `view.hitSlopRect = ...` e removeu o `setOverflow`. Mas não houve release desde setembro de 2025.

**Correção validada:** apontar para o commit do upstream. Sugiro trocar por `bun patch` antes do merge, consistente com o `patchedDependencies` que o projeto já mantém para `react-native-ios-utilities@5.2.0`. Vou abrir issue no upstream pedindo o release.

### 3. Erros de runtime após o build passar

Com o build corrigido, o app instala mas quebra na inicialização:

- `[Error: supabaseUrl is required.]` em `utils/supabase.ts:16`
- `[Error: Either a PostHog client or an apiKey is required...]` em `app/_layout.tsx:31`

O README (seção *Desenvolvimento Local*) afirma que em `__DEV__` o Supabase não é usado e o PostHog é substituído por um wrapper mock. O código não tem essa guarda em nenhum dos dois casos: `createClient()` roda no escopo global do módulo e o `PostHogProvider` recebe `apiKey` direto do `process.env`. Como o módulo do Supabase lança na avaliação, o Expo Router também emite `missing the required default export` em `onboarding.tsx`, `modal.tsx`, `events.tsx` e `menu.tsx`.

Contornado criando um `.env` com valores dummy. Não há `.env.example` no repositório.

## Como Reproduzir

1. Clonar o repositório e entrar na raiz
2. `bun install --frozen-lockfile`
3. Conectar um dispositivo Android (`adb devices` listando o aparelho)
4. `bun run:android`
5. Após ~14 min, o Gradle falha com 2 tarefas em erro: `:react-native-android-widget:compileDebugJavaWithJavac` e `:react-native-menu_menu:compileDebugKotlin`

## Comportamento Esperado

O build deveria concluir e instalar o app no dispositivo, e o app deveria iniciar em modo de desenvolvimento sem credenciais reais, conforme descrito no README.

## Screenshots

<details>
<summary>Trecho do output de `bun run:android` na main (9884b54), antes das correções</summary>
> Task :react-native-android-widget:compileDebugJavaWithJavac FAILED
/home/user/dev-workspace/development/mobile/nossa-ufsc/node_modules/react-native-android-widget/android/src/main/java/com/reactnativeandroidwidget/builder/widget/BaseWidget.java:213: error: cannot find symbol
            mReactViewBackground = new CSSBackgroundDrawable(view.getContext());
                                       ^
  symbol:   class CSSBackgroundDrawable
  location: class BaseWidget<T>
4 errors

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-menu_menu:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-android-widget:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler output below.
  /home/user/dev-workspace/development/mobile/nossa-ufsc/node_modules/react-native-android-widget/android/src/main/java/com/reactnativeandroidwidget/builder/widget/BaseWidget.java:16: error: cannot find symbol
  import com.facebook.react.uimanager.drawable.CSSBackgroundDrawable;
                                              ^
    symbol:   class CSSBackgroundDrawable
    location: package com.facebook.react.uimanager.drawable
  /home/user/dev-workspace/development/mobile/nossa-ufsc/node_modules/react-native-android-widget/android/src/main/java/com/reactnativeandroidwidget/builder/widget/BaseWidget.java:32: error: cannot find symbol
      private CSSBackgroundDrawable mReactViewBackground;
              ^
    symbol:   class CSSBackgroundDrawable
    location: class BaseWidget<T>
  /home/user/dev-workspace/development/mobile/nossa-ufsc/node_modules/react-native-android-widget/android/src/main/java/com/reactnativeandroidwidget/builder/widget/BaseWidget.java:211: error: cannot find symbol
      private CSSBackgroundDrawable getReactViewBackground() {
              ^
    symbol:   class CSSBackgroundDrawable
    location: class BaseWidget<T>
  /home/user/dev-workspace/development/mobile/nossa-ufsc/node_modules/react-native-android-widget/android/src/main/java/com/reactnativeandroidwidget/builder/widget/BaseWidget.java:213: error: cannot find symbol
              mReactViewBackground = new CSSBackgroundDrawable(view.getContext());
                                         ^
    symbol:   class CSSBackgroundDrawable
    location: class BaseWidget<T>
  4 errors

==============================================================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 10.
Gradle 9.3.1

BUILD FAILED in 13m 37s
391 actionable tasks: 255 executed, 136 from cache

Error: /home/user/dev-workspace/development/mobile/nossa-ufsc/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a exited with non-zero code: 1
    at spawnGradleAsync (node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:107:48)
    at assembleAsync (node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:82:18)
    at runAndroidAsync (node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:85:41)
error: script "android" exited with code 1
</details>

## Ambiente

- Dispositivo: Samsung SM-X400 (tablet), arm64-v8a
- OS: Android 16 (dispositivo) / Pop!_OS (host)
- Versão do App: `main` @ 9884b54
- Node: v25.2.1
- Bun: 1.3.14
- JDK: OpenJDK 21.0.9 LTS
- react-native 0.86.0 · expo ^57.0.0 · react-native-android-widget 0.17.3 (resolvida) · @react-native-menu/menu 2.0.0

## Observações adicionais

- **Sem CI.** Não há `.github/workflows/`. Um job de build Android no push teria detectado os itens 1 e 2 no commit do Expo 57.
- **`packageManager` conflitante.** O `package.json` declara `"packageManager": "pnpm@10.31.0..."`, mas o repositório tem `bun.lock` (sem `pnpm-lock.yaml`) e o README instrui Bun. Com corepack habilitado, esse campo bloqueia comandos de outros gerenciadores.
- **`overrides` no nível raiz.** O campo usa sintaxe npm/Bun; o pnpm 10 lê `pnpm.overrides`. Se a intenção era pnpm, esse override não está sendo aplicado.

Tenho as correções dos itens 1 e 2 validadas localmente (`BUILD SUCCESSFUL`, app instala e roda). Abro PR em seguida.
